import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative overflow-hidden h-screen grid grid-cols-1 md:grid-cols-3 overflow-y-auto auto-cols-max ${inter.className}`}>
        <div className="col-start-2 h-full">
          {children}
          </div>
        </body>
    </html>
  );
}
