import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import { ToastContainer, toast } from 'react-toastify';
  import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`relative overflow-hidden h-screen grid grid-cols-1 sm:grid-cols-7 overflow-y-auto auto-cols-max w-screen overflow-x-scroll ${inter.className}`}>
        
        <div className="sm:col-start-3 sm:col-end-6 h-full">
          {children}
          <ToastContainer/>
          </div>
        </body>
    </html>
  );
}
